# Generated by Django 3.2 on 2024-03-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='characteristics',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='characteristics',
            field=models.ManyToManyField(blank=True, null=True, to='vehicles.Characteristic'),
        ),
    ]
